### ISSUE TITLE
Unable to find tests

### ISSUE THREAD

**Issue by gerrypower** [lyleresnick/CleanReportTableDemo#1]
I was unable to find tests for this example. Are there any? :)

**Comment by lyleresnick** [comment]
no it yet

i will but i'm just about to release my blog about the adapter demo 
then i'll do the one on the non clean (just swiftifying)
then i'll do clean 
then i'll do tdd on clean 

but 

is there a reason you are asking ?


Lyle

**Comment by gerrypower** [comment]
Thanks!

Reason I am asking:
A) Cause it demonstrates the value
B) It will help me learn the pattern

Looking forward to it!!
